<?php

namespace Proxies\__CG__\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activites extends \MainBundle\Entity\Activites implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'nomActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'descriptionActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'prixActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'lieu', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'inscritsMax', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'ageMin', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'idActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'auteurAct', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'etatAct', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'imgAct', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'idDateAct'];
        }

        return ['__isInitialized__', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'nomActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'descriptionActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'prixActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'lieu', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'inscritsMax', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'ageMin', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'idActivite', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'auteurAct', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'etatAct', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'imgAct', '' . "\0" . 'MainBundle\\Entity\\Activites' . "\0" . 'idDateAct'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activites $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNomActivite($nomActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomActivite', [$nomActivite]);

        return parent::setNomActivite($nomActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomActivite', []);

        return parent::getNomActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionActivite($descriptionActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionActivite', [$descriptionActivite]);

        return parent::setDescriptionActivite($descriptionActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionActivite', []);

        return parent::getDescriptionActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixActivite($prixActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixActivite', [$prixActivite]);

        return parent::setPrixActivite($prixActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixActivite', []);

        return parent::getPrixActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu($lieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', [$lieu]);

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', []);

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscritsMax($inscritsMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscritsMax', [$inscritsMax]);

        return parent::setInscritsMax($inscritsMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscritsMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscritsMax', []);

        return parent::getInscritsMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgeMin($ageMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgeMin', [$ageMin]);

        return parent::setAgeMin($ageMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgeMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgeMin', []);

        return parent::getAgeMin();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdActivite()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdActivite();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdActivite', []);

        return parent::getIdActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuteurAct(\MainBundle\Entity\Users $auteurAct = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuteurAct', [$auteurAct]);

        return parent::setAuteurAct($auteurAct);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuteurAct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuteurAct', []);

        return parent::getAuteurAct();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatAct(\MainBundle\Entity\EtatsActivites $etatAct = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatAct', [$etatAct]);

        return parent::setEtatAct($etatAct);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatAct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatAct', []);

        return parent::getEtatAct();
    }

    /**
     * {@inheritDoc}
     */
    public function addImgAct(\MainBundle\Entity\Photos $imgAct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImgAct', [$imgAct]);

        return parent::addImgAct($imgAct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImgAct(\MainBundle\Entity\Photos $imgAct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImgAct', [$imgAct]);

        return parent::removeImgAct($imgAct);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgAct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgAct', []);

        return parent::getImgAct();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdDateAct(\MainBundle\Entity\Dates $idDateAct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdDateAct', [$idDateAct]);

        return parent::addIdDateAct($idDateAct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdDateAct(\MainBundle\Entity\Dates $idDateAct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdDateAct', [$idDateAct]);

        return parent::removeIdDateAct($idDateAct);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDateAct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDateAct', []);

        return parent::getIdDateAct();
    }

}
